package net.emeraldsmp.shop;
import net.emeraldsmp.EmeraldSMP;import org.bukkit.*;import org.bukkit.entity.Player;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import java.util.*;
public final class CleanSellManager{
 private static final int INPUT=45,TOTAL=47,SELL=49,CLOSE=53;private final EmeraldSMP plugin;private final Map<UUID,Inventory> open=new HashMap<>();private final Set<UUID> locks=new HashSet<>();
 public CleanSellManager(EmeraldSMP p){plugin=p;}
 public void open(Player p){close(p);Inventory inv=Bukkit.createInventory(new Holder(),54,"§2§l💚 SELL ITEMS");for(int i=45;i<54;i++)inv.setItem(i,button(Material.GRAY_STAINED_GLASS_PANE," ",List.of()));inv.setItem(TOTAL,button(Material.EMERALD,"§a§l💵 TOTAL VALUE",List.of("§7Current sell value","§f$0")));inv.setItem(SELL,button(Material.EMERALD_BLOCK,"§a§l💰 SELL",List.of("§7Sell every valid item in the input area","","§e▶ Click to sell")));inv.setItem(CLOSE,button(Material.BARRIER,"§c§l✖ CLOSE",List.of("§7Return unsold items")));open.put(p.getUniqueId(),inv);p.openInventory(inv);refresh(p);}
 public boolean isOpen(Player p,Inventory i){return open.get(p.getUniqueId())==i;}public boolean isControl(int s){return s>=45&&s<54;}public void control(Player p,int s){if(s==SELL)sell(p);else if(s==CLOSE)p.closeInventory();}
 public void refreshLater(Player p){Bukkit.getScheduler().runTask(plugin,()->{if(p.isOnline())refresh(p);});}
 private void refresh(Player p){Inventory i=open.get(p.getUniqueId());if(i==null)return;long total=0;for(int n=0;n<INPUT;n++){ItemStack x=i.getItem(n);if(x==null||x.getType().isAir())continue;try{long v=plugin.getWorthManager().sellValue(x.getType(),x.getAmount());if(v>0)total=Math.addExact(total,v);}catch(ArithmeticException e){total=Long.MAX_VALUE;break;}}i.setItem(TOTAL,button(Material.EMERALD,"§a§l💵 TOTAL VALUE",List.of("§7Current sell value","§f"+plugin.getEconomyManager().format(total))));}
 private void sell(Player p){UUID u=p.getUniqueId();if(!locks.add(u)){p.sendMessage("§e💰 Sell transaction is already processing.");return;}try{Inventory i=open.get(u);if(i==null)return;long total=0,count=0;List<Integer> slots=new ArrayList<>();List<ItemStack> items=new ArrayList<>();for(int n=0;n<INPUT;n++){ItemStack x=i.getItem(n);if(x==null||x.getType().isAir())continue;var w=plugin.getWorthManager().get(x.getType());if(w==null||!w.enabled()||w.worth()<=0)continue;try{long v=plugin.getWorthManager().sellValue(x.getType(),x.getAmount());total=Math.addExact(total,v);count=Math.addExact(count,x.getAmount());}catch(ArithmeticException e){p.sendMessage("§cThe sale is too large to process safely. Nothing was sold.");return;}slots.add(n);items.add(x.clone());}if(slots.isEmpty()||total<=0){p.sendMessage("§c❌ There are no sellable items in the sell area.");return;}for(int n:slots)i.setItem(n,null);if(!plugin.getEconomyManager().deposit(u,total)){for(int n=0;n<slots.size();n++)i.setItem(slots.get(n),items.get(n));p.sendMessage("§cThe economy rejected the transaction. Your items were restored.");refresh(p);return;}open.remove(u);p.sendMessage("§a💰 Sold §f"+String.format(Locale.US,"%,d",count)+" §aitems for §f"+plugin.getEconomyManager().format(total)+"§a.");p.closeInventory();}finally{locks.remove(u);}}
 public void close(Player p){if(locks.contains(p.getUniqueId()))return;Inventory i=open.remove(p.getUniqueId());if(i!=null)returnItems(p,i);}public void quit(Player p){close(p);}
 private void returnItems(Player p,Inventory i){for(int n=0;n<INPUT;n++){ItemStack x=i.getItem(n);if(x==null||x.getType().isAir())continue;i.setItem(n,null);for(ItemStack left:p.getInventory().addItem(x.clone()).values())p.getWorld().dropItemNaturally(p.getLocation(),left);}}
 private ItemStack button(Material m,String n,List<String>l){ItemStack i=new ItemStack(m);ItemMeta x=i.getItemMeta();if(x!=null){x.setDisplayName(n);x.setLore(l);i.setItemMeta(x);}return i;}private static final class Holder implements InventoryHolder{public Inventory getInventory(){return null;}}
}