package net.emeraldsmp.anticheat;
import net.emeraldsmp.EmeraldSMP;import org.bukkit.*;import org.bukkit.command.*;import org.bukkit.entity.Player;import org.bukkit.event.*;import org.bukkit.event.inventory.InventoryClickEvent;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.*;import java.text.SimpleDateFormat;import java.util.*;
public final class SusListCommand implements CommandExecutor,TabCompleter,Listener{private static final String LIST="§8§lEmerald AntiCheat • Suslist",DETAIL="§8§lEmerald AntiCheat • Player";private final EmeraldSMP plugin;private final SusListManager manager;public SusListCommand(EmeraldSMP p,SusListManager m){plugin=p;manager=m;}private boolean staff(Player p){return plugin.getRoleManager().isStaff(p);}
public boolean onCommand(CommandSender s,Command c,String l,String[]a){if(!(s instanceof Player p)||!staff(p)){s.sendMessage("§cOnly Emerald SMP staff can use /suslist.");return true;}if(a.length==0){list(p);return true;}if(a[0].equalsIgnoreCase("clear")){manager.clear();p.sendMessage("§a§lSUSLIST §8» §fCleared.");return true;}if(a.length>=2&&(a[0].equalsIgnoreCase("tp")||a[0].equalsIgnoreCase("remove"))){var x=find(a[1]);if(x==null){p.sendMessage("§cPlayer not found on suslist.");return true;}if(a[0].equalsIgnoreCase("tp"))p.teleport(x.location());else manager.remove(x.uuid());return true;}manager.sendList(p);return true;}
private SusListManager.Suspect find(String n){for(var s:manager.all())if(s.name().equalsIgnoreCase(n))return s;return null;}private void list(Player p){Inventory i=Bukkit.createInventory(null,54,LIST);ItemStack f=button(Material.GRAY_STAINED_GLASS_PANE," ",List.of());for(int n=0;n<54;n++)i.setItem(n,f);int slot=10;for(var s:manager.all()){if(slot>43)break;while(slot%9==0||slot%9==8)slot++;ItemStack h=new ItemStack(Material.PLAYER_HEAD);SkullMeta m=(SkullMeta)h.getItemMeta();if(m!=null){Player o=Bukkit.getPlayer(s.uuid());if(o!=null)m.setOwningPlayer(o);m.setDisplayName("§c§l⚠ "+s.name());m.setLore(List.of("§7Detection: §f"+s.reason(),"§7Violations: §c"+s.flags(),"§7Suspicion: §e"+s.suspicion()+"%","§7Status: "+(o==null?"§7Offline":"§aOnline"),"","§e▶ Click to inspect"));h.setItemMeta(m);}i.setItem(slot++,h);}i.setItem(49,button(Material.COMPASS,"§a§l🛡 SUSPICIOUS PLAYERS",List.of("§7Detection is recorded before punishment","§f"+manager.all().size()+" §7current suspect(s)")));p.openInventory(i);}
private void detail(Player p,SusListManager.Suspect s){
 Inventory i=Bukkit.createInventory(null,36,DETAIL);
 i.setItem(4,button(Material.PLAYER_HEAD,"§c§l⚠ "+s.name(),List.of(
  "§7Detection: §f"+s.reason(),
  "§7Violations: §c"+s.flags(),
  "§7Suspicion: §e"+s.suspicion()+"%",
  "§7First: §f"+time(s.firstDetectedAt()),
  "§7Last: §f"+time(s.lastDetectedAt())
 )));
 i.setItem(20,button(Material.ENDER_EYE,"§b§l👁 SPECTATE",List.of("§7Enter spectator mode and move to the player")));
 i.setItem(22,button(Material.COMPASS,"§a§l📍 TP",List.of("§7Teleport to detection location")));
 i.setItem(24,button(Material.BARRIER,"§c§l🗑 CLEAR",List.of("§7Remove this suspect")));
 i.setItem(31,button(Material.ARROW,"§e§l← BACK",List.of("§7Return to suspects")));
 p.openInventory(i);
}
private String time(long x){return x<=0?"unknown":new SimpleDateFormat("HH:mm:ss").format(new Date(x));}
@EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player p)||!staff(p))return;String t=ChatColor.stripColor(e.getView().getTitle());if(!t.equals(ChatColor.stripColor(LIST))&&!t.equals(ChatColor.stripColor(DETAIL)))return;e.setCancelled(true);int slot=e.getRawSlot();if(t.equals(ChatColor.stripColor(LIST))){ItemStack x=e.getCurrentItem();if(x==null||x.getType()!=Material.PLAYER_HEAD||!x.hasItemMeta())return;String n=ChatColor.stripColor(x.getItemMeta().getDisplayName()).replace("⚠","").trim();var s=find(n);if(s!=null)detail(p,s);return;}ItemStack h=e.getView().getTopInventory().getItem(4);if(h==null||!h.hasItemMeta())return;String n=ChatColor.stripColor(h.getItemMeta().getDisplayName()).replace("⚠","").trim();var s=find(n);if(s==null)return;switch(slot){case 20->{Player o=Bukkit.getPlayer(s.uuid());if(o==null){p.sendMessage("§cThat player is offline.");return;}p.setGameMode(GameMode.SPECTATOR);p.teleport(o.getLocation());}case 22->p.teleport(s.location());case 24->{manager.remove(s.uuid());p.sendMessage("§a🗑 Removed §f"+s.name()+" §afrom the suslist.");list(p);}case 31->list(p);default->{}}}
public List<String> onTabComplete(CommandSender s,Command c,String l,String[]a){if(a.length==2&&(a[0].equalsIgnoreCase("tp")||a[0].equalsIgnoreCase("remove"))){String q=a[1].toLowerCase(Locale.ROOT);List<String>x=new ArrayList<>();for(var z:manager.all())if(z.name().toLowerCase(Locale.ROOT).startsWith(q))x.add(z.name());return x;}return List.of("tp","remove","clear");}
private static ItemStack button(Material m,String n,List<String>l){ItemStack i=new ItemStack(m);ItemMeta x=i.getItemMeta();if(x!=null){x.setDisplayName(n);x.setLore(l);i.setItemMeta(x);}return i;}}
