package net.emeraldsmp.anticheat;
import org.bukkit.*;import org.bukkit.command.CommandSender;import org.bukkit.configuration.file.YamlConfiguration;import org.bukkit.entity.Player;import org.bukkit.plugin.java.JavaPlugin;import java.io.*;import java.util.*;
public final class SusListManager{private final JavaPlugin plugin;private final Map<UUID,Suspect> suspects=new LinkedHashMap<>();private final File file;public SusListManager(JavaPlugin p){plugin=p;file=new File(p.getDataFolder(),"suslist.yml");load();}
public synchronized void record(Player p,Location l,String type,int violations,int suspicion){UUID u=p.getUniqueId();long now=System.currentTimeMillis();Suspect s=suspects.get(u);if(s==null){s=new Suspect(u,p.getName(),l.clone(),type,violations,now,now,suspicion,new LinkedHashMap<>());suspects.put(u,s);}else{s.name=p.getName();s.location=l.clone();s.reason=type;s.flags=Math.max(s.flags,violations);s.last=now;s.suspicion=Math.max(s.suspicion,suspicion);}s.violations.merge(type.toUpperCase(Locale.ROOT),Math.max(1,violations),Math::max);save();}
public synchronized Collection<Suspect> all(){return List.copyOf(suspects.values());}public synchronized Suspect get(UUID u){return suspects.get(u);}public synchronized void remove(UUID u){suspects.remove(u);save();}public synchronized void clear(){suspects.clear();save();}public synchronized boolean has(UUID u){return suspects.containsKey(u);}
public void sendList(CommandSender s){Collection<Suspect>x=all();if(x.isEmpty()){s.sendMessage("§a§lEMERALD SUSLIST §8» §7No anti-cheat suspects.");return;}s.sendMessage("§a§lEMERALD SUSLIST §8» §f"+x.size()+" suspect(s)");for(Suspect z:x)s.sendMessage("§8• §f"+z.name+" §8» §c"+z.reason+" §8(§f"+z.flags+" violations§8) "+(Bukkit.getPlayer(z.uuid)==null?"§7OFFLINE":"§aONLINE"));}
private synchronized void save(){YamlConfiguration y=new YamlConfiguration();for(Suspect s:suspects.values()){String p="suspects."+s.uuid;y.set(p+".name",s.name);y.set(p+".reason",s.reason);y.set(p+".flags",s.flags);y.set(p+".first-detected-at",s.first);y.set(p+".last-detected-at",s.last);y.set(p+".suspicion",s.suspicion);y.set(p+".world",s.location.getWorld()==null?null:s.location.getWorld().getName());y.set(p+".x",s.location.getX());y.set(p+".y",s.location.getY());y.set(p+".z",s.location.getZ());y.set(p+".yaw",s.location.getYaw());y.set(p+".pitch",s.location.getPitch());for(var v:s.violations.entrySet())y.set(p+".violations."+v.getKey(),v.getValue());}try{if(!plugin.getDataFolder().exists())plugin.getDataFolder().mkdirs();y.save(file);}catch(IOException e){plugin.getLogger().warning("Could not save suslist.yml: "+e.getMessage());}}
private void load(){if(!file.exists())return;YamlConfiguration y=YamlConfiguration.loadConfiguration(file);var root=y.getConfigurationSection("suspects");if(root==null)return;for(String k:root.getKeys(false))try{UUID u=UUID.fromString(k);String p="suspects."+k;World w=Bukkit.getWorld(y.getString(p+".world"));if(w==null)continue;Location l=new Location(w,y.getDouble(p+".x"),y.getDouble(p+".y"),y.getDouble(p+".z"),(float)y.getDouble(p+".yaw"),(float)y.getDouble(p+".pitch"));Suspect s=new Suspect(u,y.getString(p+".name",u.toString()),l,y.getString(p+".reason","AntiCheat"),y.getInt(p+".flags"),y.getLong(p+".first-detected-at"),y.getLong(p+".last-detected-at"),y.getInt(p+".suspicion"),new LinkedHashMap<>());var vs=y.getConfigurationSection(p+".violations");if(vs!=null)for(String t:vs.getKeys(false))s.violations.put(t,vs.getInt(t));suspects.put(u,s);}catch(Exception ignored){}}
public static final class Suspect{private final UUID uuid;private String name,reason;private Location location;private int flags,suspicion;private long first,last;private final Map<String,Integer> violations;private Suspect(UUID u,String n,Location l,String r,int f,long a,long b,int s,Map<String,Integer>v){uuid=u;name=n;location=l;reason=r;flags=f;first=a;last=b;suspicion=s;violations=v;}public UUID uuid(){return uuid;}public String name(){return name;}public String reason(){return reason;}public Location location(){return location.clone();}public int flags(){return flags;}public int suspicion(){return suspicion;}public long firstDetectedAt(){return first;}public long lastDetectedAt(){return last;}public Map<String,Integer> violations(){return Collections.unmodifiableMap(violations);}}}
